name: GitHub-Profile-3D-Contrib

on:
  schedule:
    - cron: "0 */6 * * *"
  workflow_dispatch:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          
      - name: Generate profile 3D contrib
        uses: yoshi389111/github-profile-3d-contrib@0.7.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          USERNAME: imcanugur

      - name: Delete and recreate output-threeD branch
        run: |
          git push origin --delete output-threeD || echo "Branch does not exist"
          git checkout --orphan output-threeD
          git rm -rf .
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git commit --allow-empty -m "Start fresh output-threeD branch"
          git push origin output-threeD --force
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Copy only SVG files to output-threeD branch (without folder)
        run: |
          find profile-3d-contrib -name '*.svg' -exec cp {} ./ \;
        shell: bash
        
      - name: Remove profile-3d-contrib folder after copying SVGs
        run: |
          rm -rf profile-3d-contrib
        shell: bash

      - name: Commit and push only SVG files
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "generated SVGs"
          branch: output-threeD
          push_options: "--set-upstream origin output-threeD"
        env:
          GIT_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

